/**
 * Self-hosts the two typefaces as woff2 (SPEC §9): they must not be loaded
 * from Google's CDN at runtime — that is an extra connection on a mobile
 * network and a privacy leak.
 *
 * Fetches the latin + latin-ext subsets once and writes them, plus a
 * generated @font-face block, into public/fonts/.
 *
 *   npm run fonts
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const OUT = fileURLToPath(new URL('../public/fonts/', import.meta.url));
const FACE_CSS = new URL('../src/styles/fonts.css', import.meta.url);

// A modern UA string is what makes the API serve woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  'Spectral:ital,wght@0,300;0,400;0,600;1,300;1,400;1,600',
  'Barlow+Condensed:wght@500;600',
];

// Only these subsets are needed: the prose is English with botanical Latin.
const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

interface Face {
  family: string;
  style: string;
  weight: string;
  unicodeRange: string;
  url: string;
  subset: string;
  file: string;
}

function parseCss(css: string): Face[] {
  const faces: Face[] = [];
  const blocks = css.split('@font-face').slice(1);
  let subset = '';
  // Google annotates each block with a `/* latin */` style comment.
  const commentRe = /\/\*\s*([a-z0-9-]+)\s*\*\//gi;
  const comments = [...css.matchAll(commentRe)].map((m) => ({ index: m.index ?? 0, name: m[1] }));

  let cursor = css.indexOf('@font-face');
  for (const block of blocks) {
    const blockStart = cursor;
    cursor = css.indexOf('@font-face', cursor + 1);
    const preceding = comments.filter((c) => c.index < blockStart).pop();
    subset = preceding?.name ?? 'latin';

    const pick = (prop: string) =>
      new RegExp(`${prop}:\\s*([^;]+);`).exec(block)?.[1]?.trim() ?? '';
    const url = /src:[^;]*url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    if (!url) continue;

    const family = pick('font-family').replace(/['"]/g, '');
    const style = pick('font-style') || 'normal';
    const weight = pick('font-weight') || '400';
    const unicodeRange = pick('unicode-range');
    const stem = family.toLowerCase().replace(/\s+/g, '-');
    const file = `${stem}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
    faces.push({ family, style, weight, unicodeRange, url, subset, file });
  }
  return faces;
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const all: Face[] = [];

  for (const family of FAMILIES) {
    const href = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
    const res = await fetch(href, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${href} -> ${res.status}`);
    all.push(...parseCss(await res.text()).filter((f) => WANTED_SUBSETS.has(f.subset)));
  }

  let bytes = 0;
  for (const face of all) {
    const res = await fetch(face.url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${face.url} -> ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    bytes += buf.byteLength;
    await writeFile(new URL(face.file, `file://${OUT}`), buf);
    console.log(`  ${face.file}  ${(buf.byteLength / 1024).toFixed(1)} KB`);
  }

  // The `__BASE__` token is substituted with import.meta.env.BASE_URL by
  // BaseLayout, so the font URLs stay correct if the site is ever served from
  // a project subpath rather than a domain root (SPEC §2).
  const css = [
    '/* Generated by scripts/fonts.ts — do not edit by hand. Run: npm run fonts */',
    ...all.map((f) =>
      [
        '@font-face {',
        `  font-family: '${f.family}';`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        '  font-display: swap;',
        `  src: url('__BASE__fonts/${f.file}') format('woff2');`,
        f.unicodeRange ? `  unicode-range: ${f.unicodeRange};` : '',
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    ),
  ].join('\n\n');

  await writeFile(FACE_CSS, css + '\n');
  console.log(`\n${all.length} faces, ${(bytes / 1024).toFixed(0)} KB total -> public/fonts/`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
